language: python
sudo: false
python:
  - "3.6"
  
before_install:
  - pip install -U pip
install:
  - travis_wait travis_retry pip install pytest
  - travis_wait travis_retry pip install git+https://github.com/david-leon/Lasagne_CTC.git
  - travis_wait travis_retry pip install git+https://github.com/david-leon/Lasagne_Ext.git
  - travis_wait travis_retry pip install git+https://github.com/Theano/Theano.git#egg=Theano
  - travis_retry python setup.py install
script: pytest Test/Test_Dense.py -v

cache:
  - directories:
    - $HOME/.theano
